---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 3m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.2.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    server:
      persistentVolume:
        enabled: false

    alertmanager:
      persistence:
        enabled: false
