---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gotk-components-v2.2.3.yaml

patches:
  - path: disallow-force-push.yaml
    target:
      version: apps/v1
      kind: Deployment
      name: image-automation-controller
      namespace: flux-system
